# Generated by Django 3.1.1 on 2020-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0002_auto_20200926_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Video Upload'),
        ),
    ]
