# Generated by Django 3.1.1 on 2020-09-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0003_mywork_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mywork',
            new_name='filestorage',
        ),
    ]
