# Generated by Django 3.1.1 on 2020-09-26 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0005_filestorage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='time',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 26), null=True),
        ),
    ]
