# Generated by Django 3.1.1 on 2020-09-26 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0007_auto_20200926_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 26, 16, 16, 31, 612553, tzinfo=utc), null=True),
        ),
    ]
