# Generated by Django 3.1 on 2020-09-27 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portnew', '0015_auto_20200927_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserID',
            new_name='Users',
        ),
    ]
