# Generated by Django 3.1 on 2020-09-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0016_auto_20200927_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
