# Generated by Django 3.1 on 2020-09-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0018_auto_20200927_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
