# Generated by Django 3.1 on 2020-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0019_auto_20200927_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='video',
        ),
        migrations.AddField(
            model_name='filestorage',
            name='file_up',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File Upload'),
        ),
    ]
