# Generated by Django 3.1 on 2020-10-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0025_auto_20201013_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='image3',
        ),
    ]
