# Generated by Django 3.1 on 2020-10-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portnew', '0026_auto_20201013_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='username',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='filestorage',
        ),
    ]
